consumes:
- application/json
info:
  title: customer-api
  version: 0.1.0
paths:
  /:
    get:
      tags:
        - customers
      operationId: list_customers
      parameters:
        - name: name
          in: query
          type: string
        - name: lastname
          in: query
          type: string
      responses:
        200:
          description: list the todo operations
          schema:
            type: array
            items:
              $ref: "#/definitions/item"
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/error"
definitions:
  item:
    type: object
    required:
      - status
    properties:
      id:
        type: integer
        format: int64
        readOnly: true
      name:
        type: string
      lastName:
        type: string
      status:
        type: boolean
  error:
    type: object
    required:
      - message
    properties:
      code:
        type: integer
        format: int64
      message:
        type: string            
produces:
- application/json
schemes:
- http
swagger: "2.0"
