// Code generated by go-swagger; DO NOT EDIT.

package customers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/mateusprado/go-swagger-example/models"
)

// ListCustomersOKCode is the HTTP code returned for type ListCustomersOK
const ListCustomersOKCode int = 200

/*ListCustomersOK list the todo operations

swagger:response listCustomersOK
*/
type ListCustomersOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Item `json:"body,omitempty"`
}

// NewListCustomersOK creates ListCustomersOK with default headers values
func NewListCustomersOK() *ListCustomersOK {

	return &ListCustomersOK{}
}

// WithPayload adds the payload to the list customers o k response
func (o *ListCustomersOK) WithPayload(payload []*models.Item) *ListCustomersOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list customers o k response
func (o *ListCustomersOK) SetPayload(payload []*models.Item) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListCustomersOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make([]*models.Item, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

/*ListCustomersDefault generic error response

swagger:response listCustomersDefault
*/
type ListCustomersDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewListCustomersDefault creates ListCustomersDefault with default headers values
func NewListCustomersDefault(code int) *ListCustomersDefault {
	if code <= 0 {
		code = 500
	}

	return &ListCustomersDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the list customers default response
func (o *ListCustomersDefault) WithStatusCode(code int) *ListCustomersDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the list customers default response
func (o *ListCustomersDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the list customers default response
func (o *ListCustomersDefault) WithPayload(payload *models.Error) *ListCustomersDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list customers default response
func (o *ListCustomersDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListCustomersDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
